// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	sql "github.com/dnonakolesax/noted-auth/internal/db/sql"
	mock "github.com/stretchr/testify/mock"
)

// MockIPGXWorker is an autogenerated mock type for the IPGXWorker type
type MockIPGXWorker struct {
	mock.Mock
}

type MockIPGXWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPGXWorker) EXPECT() *MockIPGXWorker_Expecter {
	return &MockIPGXWorker_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, _a1, args
func (_m *MockIPGXWorker) Exec(ctx context.Context, _a1 string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, _a1, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPGXWorker_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIPGXWorker_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - args ...interface{}
func (_e *MockIPGXWorker_Expecter) Exec(ctx interface{}, _a1 interface{}, args ...interface{}) *MockIPGXWorker_Exec_Call {
	return &MockIPGXWorker_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, _a1}, args...)...)}
}

func (_c *MockIPGXWorker_Exec_Call) Run(run func(ctx context.Context, _a1 string, args ...interface{})) *MockIPGXWorker_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIPGXWorker_Exec_Call) Return(_a0 error) *MockIPGXWorker_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPGXWorker_Exec_Call) RunAndReturn(run func(context.Context, string, ...interface{}) error) *MockIPGXWorker_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, _a1, args
func (_m *MockIPGXWorker) Query(ctx context.Context, _a1 string, args ...interface{}) (*sql.PGXResponse, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.PGXResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (*sql.PGXResponse, error)); ok {
		return rf(ctx, _a1, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.PGXResponse); ok {
		r0 = rf(ctx, _a1, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.PGXResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, _a1, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPGXWorker_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockIPGXWorker_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - args ...interface{}
func (_e *MockIPGXWorker_Expecter) Query(ctx interface{}, _a1 interface{}, args ...interface{}) *MockIPGXWorker_Query_Call {
	return &MockIPGXWorker_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, _a1}, args...)...)}
}

func (_c *MockIPGXWorker_Query_Call) Run(run func(ctx context.Context, _a1 string, args ...interface{})) *MockIPGXWorker_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIPGXWorker_Query_Call) Return(_a0 *sql.PGXResponse, _a1 error) *MockIPGXWorker_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPGXWorker_Query_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (*sql.PGXResponse, error)) *MockIPGXWorker_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPGXWorker creates a new instance of MockIPGXWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPGXWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPGXWorker {
	mock := &MockIPGXWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
