// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson53c2c5caDecodeGithubComDnonakolesaxNotedAuthInternalModel(in *jlexer.Lexer, out *HealthcheckDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "redis_alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RedisAlive = bool(in.Bool())
			}
		case "postgres_alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PostgresAlive = bool(in.Bool())
			}
		case "keycloak_alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.KeycloakAlive = bool(in.Bool())
			}
		case "vault_alive":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VaultAlive = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson53c2c5caEncodeGithubComDnonakolesaxNotedAuthInternalModel(out *jwriter.Writer, in HealthcheckDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"redis_alive\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.RedisAlive))
	}
	{
		const prefix string = ",\"postgres_alive\":"
		out.RawString(prefix)
		out.Bool(bool(in.PostgresAlive))
	}
	{
		const prefix string = ",\"keycloak_alive\":"
		out.RawString(prefix)
		out.Bool(bool(in.KeycloakAlive))
	}
	{
		const prefix string = ",\"vault_alive\":"
		out.RawString(prefix)
		out.Bool(bool(in.VaultAlive))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthcheckDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson53c2c5caEncodeGithubComDnonakolesaxNotedAuthInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthcheckDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson53c2c5caEncodeGithubComDnonakolesaxNotedAuthInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthcheckDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson53c2c5caDecodeGithubComDnonakolesaxNotedAuthInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthcheckDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson53c2c5caDecodeGithubComDnonakolesaxNotedAuthInternalModel(l, v)
}
