// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF041b085DecodeGithubComDnonakolesaxNotedAuthInternalModel(in *jlexer.Lexer, out *TokenDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "expires_in":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiresIn = int(in.Int())
			}
		case "refresh_expires_in":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RefreshExp = int(in.Int())
			}
		case "refresh_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RefreshToken = string(in.String())
			}
		case "token_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenType = string(in.String())
			}
		case "not-before-policy":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NotBeforePolicy = int(in.Int())
			}
		case "session_state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SessionState = string(in.String())
			}
		case "scope":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Scope = string(in.String())
			}
		case "return_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReturnURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF041b085EncodeGithubComDnonakolesaxNotedAuthInternalModel(out *jwriter.Writer, in TokenDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"expires_in\":"
		out.RawString(prefix)
		out.Int(int(in.ExpiresIn))
	}
	{
		const prefix string = ",\"refresh_expires_in\":"
		out.RawString(prefix)
		out.Int(int(in.RefreshExp))
	}
	{
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix)
		out.String(string(in.RefreshToken))
	}
	{
		const prefix string = ",\"token_type\":"
		out.RawString(prefix)
		out.String(string(in.TokenType))
	}
	{
		const prefix string = ",\"not-before-policy\":"
		out.RawString(prefix)
		out.Int(int(in.NotBeforePolicy))
	}
	{
		const prefix string = ",\"session_state\":"
		out.RawString(prefix)
		out.String(string(in.SessionState))
	}
	{
		const prefix string = ",\"scope\":"
		out.RawString(prefix)
		out.String(string(in.Scope))
	}
	{
		const prefix string = ",\"return_url\":"
		out.RawString(prefix)
		out.String(string(in.ReturnURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TokenDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF041b085EncodeGithubComDnonakolesaxNotedAuthInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TokenDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF041b085EncodeGithubComDnonakolesaxNotedAuthInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TokenDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF041b085DecodeGithubComDnonakolesaxNotedAuthInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TokenDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF041b085DecodeGithubComDnonakolesaxNotedAuthInternalModel(l, v)
}
