// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC331b5d2DecodeGithubComDnonakolesaxNotedAuthInternalModel(in *jlexer.Lexer, out *UserID) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC331b5d2EncodeGithubComDnonakolesaxNotedAuthInternalModel(out *jwriter.Writer, in UserID) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserID) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC331b5d2EncodeGithubComDnonakolesaxNotedAuthInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserID) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC331b5d2EncodeGithubComDnonakolesaxNotedAuthInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserID) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC331b5d2DecodeGithubComDnonakolesaxNotedAuthInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserID) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC331b5d2DecodeGithubComDnonakolesaxNotedAuthInternalModel(l, v)
}
